// Objective-C API for talking to github.com/skycoin/skycoin-lite/mobile Go package.
//   gobind -lang=objc github.com/skycoin/skycoin-lite/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * GetAddresses generates num addresses from seed using
the Skycoin deterministic address generator
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetAddresses(NSString* _Nullable seed, long num, NSError* _Nullable* _Nullable error);

/**
 * NewWordSeed wraps bip39.NewDefaultMnemonic
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileNewWordSeed(NSError* _Nullable* _Nullable error);

/**
 * PrepareTransaction receives inputs and outputs and returns a signed transaction
inputsBody and outputsBody are JSONified arrays of TransactionInput and TransactionOutput.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobilePrepareTransaction(NSString* _Nullable inputsBody, NSString* _Nullable outputsBody, NSError* _Nullable* _Nullable error);

#endif
